#!/usr/bin/env bash
#anothercomment bad luck whatever

counter=1
while [ "$counter" -le 10 ] 
do
 if [ "$counter" -eq 4 ]; then
   echo "bad luck"
   counter=$((counter+1))
 elif [ "$counter" -eq 8 ];then
   echo "good luck"
   counter=$((counter+1))
 else
   echo "Best School"
   counter=$((counter+1))
 fi
done
