#!/usr/bin/env bash
# clockin

hour=0
second=1

while [ "$hour" -le 12 ]
do
  echo "Hour: $hour"
  while [ "$second" -lt 60 ]
  do
    echo "$second"
    second=$((second+1))
  done
  second=1
  hour=$((hour+1))
done

